### PR TITLE
feat: add directory input

### PR DESCRIPTION
**Pull request by shouze**
## Description

Please include a summary of the change and/or issue that is being worked on. Please also include relevant motivation and context. List any dependencies that are required for this change.

Adds Feature or Fixes: # (issue)

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] The test workflow is passing locally

### CODE REVIEW

**Comment by cody-hoffman** [comment]
Thanks for the PR @shouze were you able to verify this change locally?

**Comment by shouze** [comment]
@cody-hoffman yes for sure. We already have 3 steps in 2 github workflows using this feature. As we have a git mono repository with many apps it's helpful :wink:

**Comment by cody-hoffman** [comment]
Awesome :+1: I'll merge and release, thanks for contributing.

**Review by cody-hoffman — APPROVED** [review]

**Comment by cody-hoffman** [comment]
Published in release [0.0.5](https://github.com/TractorZoom/sam-cli-action/releases/tag/0.0.5)

**Pull request merged**
